### ISSUE TITLE
UX issue in Chrome 

### ISSUE THREAD

**Issue by augustusCade** [dracula/react-devtools#1]
Currently in Chrome Version 81.0.4044.113 (Official Build) (64-bit)

Highlighted the issue at the top of the verticle dev console in the below  screenshot. 
![Screen Shot 2020-04-23 at 11 00 43 PM](https://user-images.githubusercontent.com/16404971/80174198-88de4980-85b7-11ea-85fc-c3dfd75d04bf.png)

**Comment by zenorocha** [comment]
Closing since it's no longer valid.
