### ISSUE TITLE
Not available in React DevTools v4

### ISSUE THREAD

**Issue by cmrn** [dracula/react-devtools#2]
Custom themes are no longer supported in React DevTools - see https://github.com/facebook/react/issues/16452

This should probably be noted in the README / website.

**Comment by jvbs** [comment]
This issue persists in 2021.

**Comment by cmrn** [comment]
@zenorocha maybe it's time to delete this repo... 😓

**Comment by cmrn** [comment]
@zenorocha maybe it's time to delete this repo... 😓

**Comment by pabloherrero1986** [comment]
yeah @zenorocha I think the same, delete this repo...

**Comment by zenorocha** [comment]
Thanks everybody! Archiving the repo now...

**Comment by zenorocha** [comment]
https://github.com/dracula/draculatheme.com/commit/1d5e1de09fd1ec574c80e6a0eed1e28425801995
https://github.com/dracula/dracula-theme/commit/423f2c831debbb7ae291337cf8a3873457831c5e
